# Generated by Django 5.0.4 on 2024-04-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_relevant', models.IntegerField(blank=True, null=True, verbose_name='Отзыв релевантный?')),
                ('object', models.IntegerField(blank=True, choices=[(0, 'Вэбинар'), (1, 'Программа'), (2, 'Преподаватель')], null=True, verbose_name='К чему относятся?')),
                ('is_positive', models.IntegerField(blank=True, null=True, verbose_name='Отзыв положительный?')),
                ('answers', models.ManyToManyField(to='api.answer', verbose_name='Ответы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Набор для нейросети',
                'verbose_name_plural': 'Наборы для нейросети',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='Вопрос'),
        ),
    ]
